version: '2.1'

services:
  
  # ------------------------------------------------------------------------------------
  # Node-RED
  # ------------------------------------------------------------------------------------
  node-red:
    build: ./node-red 
    privileged: true
    restart: unless-stopped
    depends_on:
        - industrial-shields
    volumes:
        - 'node-red-data:/data'
    labels:
        io.balena.features.dbus: '1'
        io.balena.features.sysfs: '1'
        io.balena.features.supervisor-api: '1'
        io.balena.features.balena-api: '1'
        io.balena.features.balena-socket: '1'
        io.balena.features.kernel-modules: '1'
        io.balena.features.firmware: '1'
    ports:
        - 80:80
    environment:
        - PORT=80
        - USERNAME="balena"
        - PASSWORD="balena"
        - ENCRIPTION_KEY="balena"
        - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
    cap_add:
        - SYS_RAWIO

  # ------------------------------------------------------------------------------------
  # Industrial Shields PLC for RPi
  # ------------------------------------------------------------------------------------
  industrial-shields:
    build: ./industrial-shields 
    privileged: true
    restart: unless-stopped
    labels:
        io.balena.features.dbus: '1'
        io.balena.features.sysfs: '1'
        io.balena.features.supervisor-api: '1'
        io.balena.features.balena-api: '1'
        io.balena.features.balena-socket: '1'
        io.balena.features.kernel-modules: '1'
        io.balena.features.firmware: '1'
    cap_add:
        - SYS_RAWIO
    devices:
        - "/dev/mem:/dev/mem"
        - "/dev/gpiomem:/dev/gpiomem"
        - "/dev/i2c-1:/dev/i2c-1"
        - "/dev/ttyUSB0:/dev/ttyUSB0"
        - "/dev/ttySC0:/dev/ttySC0"
        - "/dev/ttySC1:/dev/ttySC1"
        - "/dev/ttySC2:/dev/ttySC2"
        - "/dev/ttySC3:/dev/ttySC3"

volumes:
  node-red-data:
